import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { demoProducts, uiText } from "@/constants/content";
import { PageContainer } from "@/components/shared/page-container";
import { Breadcrumb } from "@/components/shared/breadcrumb";
import { ResponsiveImage } from "@/components/shared/responsive-image";
import { ProductCard } from "@/components/product/product-card";
import { PriceDisplay } from "@/components/product/price-display";
import { Badge } from "@/components/ui/badge";
import { Alert } from "@/components/ui/alert";
import { SectionHeading } from "@/components/shared/section-heading";
import { siteConfig } from "@/config/site";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return demoProducts.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const product = demoProducts.find((item) => item.slug === slug); return product ? { title: product.name, description: `${product.description} تفاصيل نسخة العرض مبدئية حتى اعتماد ملف المنتج الرسمي.`, alternates: { canonical: `/products/${slug}` }, openGraph: { title: product.name, description: product.description, images: [{ url: "/images/product-still-life.webp", alt: `صورة عرض لـ${product.name}` }] } } : { title: "منتج غير موجود" }; }
export default async function ProductPage({ params }: Props) { const { slug } = await params; const product = demoProducts.find((item) => item.slug === slug); if (!product) notFound(); const related = demoProducts.filter((item) => item.slug !== slug && item.categorySlug === product.categorySlug).concat(demoProducts.filter((item) => item.slug !== slug && item.categorySlug !== product.categorySlug)).slice(0, 3); const breadcrumbData = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "الرئيسية", item: new URL("/", siteConfig.url).toString() }, { "@type": "ListItem", position: 2, name: "المنتجات", item: new URL("/products", siteConfig.url).toString() }, { "@type": "ListItem", position: 3, name: product.name, item: new URL(`/products/${product.slug}`, siteConfig.url).toString() }] }; return <PageContainer><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbData) }} /><Breadcrumb items={[{ label: "الرئيسية", href: "/" }, { label: "المنتجات", href: "/products" }, { label: product.name }]} /><section className="product-detail"><div className="product-gallery"><ResponsiveImage alt={`صورة عبوة ${product.name}`} tone={product.tone} position={product.imagePosition} priority /></div><div className="product-summary"><div className="product-summary__top"><Badge>{product.category}</Badge><span className={product.available ? "availability" : "availability availability--soon"}>{product.availability}</span></div><h1>{product.name}</h1><p className="product-summary__lead">{product.description}</p><div className="product-summary__price"><PriceDisplay amount={product.price} currency={product.currency} /><small>سعر مبدئي للعرض — تُعتمد العملة لاحقًا</small></div><fieldset className="variant-field"><legend>الحجم المتاح للعرض</legend><div className="option-row">{product.sizes.map((size, index) => <label className="variant-option" key={size}><input type="radio" name="size" defaultChecked={index === 0} /><span>{size}</span></label>)}</div></fieldset><Link className="link-button product-action" href="/cart">استكشفي تجربة الطلب القادمة</Link><p className="product-action-note">تُفعّل الطلبات بعد اعتماد الأسعار والشحن والدفع.</p><div className="micro-features"><span>معلومات قابلة للتحديث</span><span>تحذيرات في موضع واضح</span><span>لا وعود علاجية</span></div></div></section>
  <section className="product-information"><div className="product-information__nav" aria-label="أقسام معلومات المنتج"><a href="#overview">نظرة عامة</a><a href="#ingredients">المكونات</a><a href="#usage">الاستخدام</a><a href="#safety">السلامة</a></div><div className="product-information__content"><article id="overview"><p className="eyebrow">نظرة عامة</p><h2>تفاصيل واضحة لاختيار أكثر ثقة</h2><p>{product.overview}</p></article><article id="ingredients"><p className="eyebrow">المكونات</p><h2>شفافية تبدأ من ملصق المنتج</h2><p>تُنشر قائمة المكونات ومعلومات الحساسية كما ترد في ملف المنتج الرسمي، دون اختصار أو تخمين.</p></article><article id="usage"><p className="eyebrow">كيف يُستخدم</p><h2>خطوة واضحة داخل الروتين</h2><p>تظهر طريقة الاستخدام والتكرار والترتيب داخل الروتين وفق تعليمات المنتج الرسمية عند اعتمادها.</p></article><article><p className="eyebrow">دليل التوافق</p><h2>لمن صُمم هذا الاختيار؟</h2><div className="tag-list">{product.skinTypes.map((item) => <span key={item}>{item}</span>)}{product.concerns.map((item) => <span key={item}>{item}</span>)}</div><p>التوافق المعروض يوضح طريقة تنظيم الكتالوج، ويُراجع مع ملف المنتج الرسمي قبل الإطلاق.</p></article><article id="safety"><Alert title="تنبيه السلامة" tone="error">راجعي قائمة المكونات والتحذيرات المعتمدة مستقبلًا. {uiText.medicalNotice} {uiText.seriousNotice}</Alert></article><article><p className="eyebrow">التخزين</p><h2>حفظ الجودة يبدأ بالتخزين</h2><p>تُعرض هنا درجة الحرارة ومدة الصلاحية وطريقة الحفظ كما يحددها ملف المنتج الرسمي.</p></article><article><p className="eyebrow">أسئلة عن المنتج</p><div className="faq-list"><details><summary>هل يناسب هذا المنتج نوع بشرتي؟</summary><p>التوافق الظاهر مبدئي، ويصبح مرجعًا للاختيار بعد مراجعة مكونات المنتج وتعليماته الرسمية.</p></details><details><summary>هل السعر والحجم نهائيان؟</summary><p>القيم المعروضة مبدئية، وتُحدّث فور اعتماد الكتالوج الرسمي.</p></details><details><summary>هل يمكن طلبه الآن؟</summary><p>تجربة الطلب قادمة، وتُفعّل بعد اعتماد الأسعار والشحن والدفع.</p></details></div></article></div></section>
  <section className="section"><SectionHeading eyebrow="قد يعجبك أيضًا" title="منتجات أخرى ضمن العرض" /><div className="product-grid">{related.map((item) => <ProductCard key={item.slug} product={item} />)}</div><p className="center"><Link className="text-link" href="/products">العودة إلى كل المنتجات ←</Link></p></section></PageContainer>; }
