"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireSession } from "@/server/auth/session";
import { getDb } from "@/server/db/client";
import { auth } from "@/server/auth/auth";
import { headers } from "next/headers";

const profileSchema=z.object({name:z.string().trim().min(2).max(100),phone:z.string().trim().max(30).optional()});
const addressSchema=z.object({id:z.string().uuid().optional(),label:z.string().trim().max(40).optional(),recipient:z.string().trim().min(2).max(100),phone:z.string().trim().min(6).max(30),countryCode:z.string().trim().min(2).max(60),city:z.string().trim().min(2).max(80),area:z.string().trim().max(80).optional(),street:z.string().trim().min(2).max(160),building:z.string().trim().max(80).optional(),postalCode:z.string().trim().max(20).optional(),notes:z.string().trim().max(300).optional(),isDefault:z.coerce.boolean().default(false)});
async function audit(userId:string,action:string,resourceType:string,resourceId?:string){await getDb().auditLog.create({data:{actorUserId:userId,action,resourceType,resourceId,outcome:"SUCCESS"}})}

export async function updateProfile(formData:FormData){const {user}=await requireSession();const parsed=profileSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return;await getDb().$transaction(async db=>{await db.user.update({where:{id:user.id},data:{name:parsed.data.name}});await db.customerProfile.upsert({where:{userId:user.id},create:{userId:user.id,phone:parsed.data.phone||null},update:{phone:parsed.data.phone||null}})});await audit(user.id,"PROFILE_UPDATED","User",user.id);revalidatePath("/account/profile");}
export async function saveAddress(formData:FormData){const {user}=await requireSession();const raw=Object.fromEntries(formData);const parsed=addressSchema.safeParse({...raw,isDefault:raw.isDefault==="on"});if(!parsed.success)return;const {id,isDefault,...data}=parsed.data;const db=getDb();const saved=await db.$transaction(async tx=>{if(isDefault)await tx.address.updateMany({where:{userId:user.id,deletedAt:null},data:{isDefault:false}});if(id){const owned=await tx.address.findFirst({where:{id,userId:user.id,deletedAt:null}});if(!owned)throw new Error("NOT_FOUND");return tx.address.update({where:{id},data:{...data,isDefault}})}return tx.address.create({data:{...data,isDefault,userId:user.id}})});await audit(user.id,id?"ADDRESS_UPDATED":"ADDRESS_CREATED","Address",saved.id);revalidatePath("/account/addresses");}
export async function deleteAddress(id:string){const {user}=await requireSession();const owned=await getDb().address.findFirst({where:{id,userId:user.id,deletedAt:null}});if(!owned)return;await getDb().address.update({where:{id},data:{deletedAt:new Date(),isDefault:false}});await audit(user.id,"ADDRESS_DELETED","Address",id);revalidatePath("/account/addresses");}
export async function setDefaultAddress(id:string){const {user}=await requireSession();const db=getDb();await db.$transaction(async tx=>{const owned=await tx.address.findFirst({where:{id,userId:user.id,deletedAt:null}});if(!owned)throw new Error("NOT_FOUND");await tx.address.updateMany({where:{userId:user.id,deletedAt:null},data:{isDefault:false}});await tx.address.update({where:{id},data:{isDefault:true}})});revalidatePath("/account/addresses");}
export async function changePassword(formData:FormData){await requireSession();const currentPassword=String(formData.get("currentPassword")||"");const newPassword=String(formData.get("newPassword")||"");if(newPassword.length<8||newPassword!==String(formData.get("confirmPassword")||""))return;try{await auth.api.changePassword({headers:await headers(),body:{currentPassword,newPassword,revokeOtherSessions:true}});}catch{return;}}
