import { PrismaPg } from "@prisma/adapter-pg";
import { CouponType, PrismaClient, ProductStatus, RecordStatus } from "../generated/prisma/client";

const connectionString=process.env.DATABASE_URL;if(!connectionString)throw new Error("DATABASE_URL is required to seed DEMO DATA.");const prisma=new PrismaClient({adapter:new PrismaPg({connectionString})});
async function main(){
  const face=await prisma.productCategory.upsert({where:{slug:"demo-face-oils"},update:{status:RecordStatus.ACTIVE},create:{slug:"demo-face-oils",nameAr:"زيوت الوجه التجريبية",descriptionAr:"فئة تطوير غير معتمدة تجاريًا.",status:RecordStatus.ACTIVE}});
  const simple=await prisma.productCategory.upsert({where:{slug:"demo-simple-care"},update:{status:RecordStatus.ACTIVE},create:{slug:"demo-simple-care",nameAr:"العناية البسيطة التجريبية",descriptionAr:"فئة تطوير غير معتمدة تجاريًا.",status:RecordStatus.ACTIVE}});
  const products=[
    {slug:"daily-balance-oil",nameAr:"زيت التوازن اليومي",categoryId:face.id,sku:"DEMO-DBO-15",size:"15 مل",price:"180.00",stock:12},
    {slug:"gentle-night-oil",nameAr:"زيت المساء اللطيف",categoryId:face.id,sku:"DEMO-GNO-30",size:"30 مل",price:"220.00",stock:2},
    {slug:"simple-care-oil",nameAr:"زيت العناية البسيطة",categoryId:simple.id,sku:"DEMO-SCO-15",size:"15 مل",price:"160.00",stock:0},
    {slug:"soft-routine-oil",nameAr:"زيت الروتين الهادئ",categoryId:face.id,sku:"DEMO-SRO-30",size:"30 مل",price:"195.00",stock:8},
    {slug:"everyday-oil",nameAr:"زيت كل يوم",categoryId:simple.id,sku:"DEMO-EDO-15",size:"15 مل",price:"150.00",stock:6},
  ];
  for(const item of products){const product=await prisma.product.upsert({where:{slug:item.slug},update:{nameAr:item.nameAr,categoryId:item.categoryId,status:ProductStatus.ACTIVE,deletedAt:null},create:{slug:item.slug,nameAr:item.nameAr,categoryId:item.categoryId,shortDescriptionAr:"بيانات تجريبية للعرض التقني فقط.",descriptionAr:"منتج خيالي لا يمثل تركيبة أو ادعاء تجاريًا حقيقيًا.",usageAr:"طريقة الاستخدام قيد الاعتماد.",safetyNoticeAr:"تحذيرات السلامة قيد مراجعة مختص.",status:ProductStatus.ACTIVE}});await prisma.productVariant.upsert({where:{sku:item.sku},update:{productId:product.id,nameAr:item.size,sizeLabel:item.size,price:item.price,currency:"XXX",stock:item.stock,isActive:true,deletedAt:null},create:{productId:product.id,sku:item.sku,nameAr:item.size,sizeLabel:item.size,price:item.price,currency:"XXX",stock:item.stock,isActive:true}});}
  const now=new Date(),yesterday=new Date(now.getTime()-86400000),tomorrow=new Date(now.getTime()+86400000*30);
  const coupons=[
    {code:"KIKA10",type:CouponType.PERCENTAGE,value:"10",minimumSubtotal:"100",maximumDiscount:"50",startsAt:yesterday,endsAt:tomorrow,usageLimit:100,perCustomerLimit:1,isActive:true},
    {code:"WELCOME25",type:CouponType.FIXED,value:"25",minimumSubtotal:"200",maximumDiscount:null,startsAt:yesterday,endsAt:tomorrow,usageLimit:20,perCustomerLimit:1,isActive:true},
    {code:"EXPIRED10",type:CouponType.PERCENTAGE,value:"10",minimumSubtotal:null,maximumDiscount:null,startsAt:new Date(now.getTime()-86400000*30),endsAt:yesterday,usageLimit:100,perCustomerLimit:1,isActive:true},
    {code:"LIMITED5",type:CouponType.FIXED,value:"5",minimumSubtotal:null,maximumDiscount:null,startsAt:yesterday,endsAt:tomorrow,usageLimit:1,perCustomerLimit:1,isActive:true},
  ];
  for(const c of coupons)await prisma.coupon.upsert({where:{code:c.code},update:{...c,currency:"XXX",isDemo:true},create:{...c,currency:"XXX",isDemo:true}});
  await prisma.siteSetting.upsert({where:{key:"phase4_commerce_demo"},update:{value:{demo:true,currency:"XXX",shipping:25,cod:true,bankTransfer:true}},create:{key:"phase4_commerce_demo",value:{demo:true,currency:"XXX",shipping:25,cod:true,bankTransfer:true},isPublic:false}});
  const template=await prisma.assessmentTemplate.upsert({where:{key_version:{key:"skin-guidance-demo",version:1}},update:{status:RecordStatus.ACTIVE},create:{key:"skin-guidance-demo",nameAr:"تقييم تحضير إرشاد البشرة — مبدئي",version:1,status:RecordStatus.ACTIVE,consentVersion:"assessment-demo-v1",estimatedMinutes:7,isProvisional:true,publishedAt:new Date()}});
  const sectionKeys=["basic","characteristics","safety","screening","routine","actives","goals","preferences"];
  const sections=new Map<string,string>();
  for(let i=0;i<sectionKeys.length;i++){const key=sectionKeys[i];const row=await prisma.assessmentSection.upsert({where:{templateId_key:{templateId:template.id,key}},update:{sortOrder:i},create:{templateId:template.id,key,titleAr:key,sortOrder:i}});sections.set(key,row.id)}
  const questions=[
    ["age_group","الفئة العمرية","basic",true,["أقل من 16","16–24","25–34","35–44","45 أو أكثر"]],
    ["after_cleansing","كيف يكون إحساس بشرتك عادة بعد التنظيف؟","characteristics",true,["مريح","مشدود أو جاف","دهني سريعًا","غير متأكدة"]],
    ["oiliness","كيف تصفين مستوى الزيوت الظاهرة؟","characteristics",true,["قليل","متوسط","مرتفع","يتغير"]],
    ["dryness","كيف تصفين الإحساس بالجفاف؟","characteristics",true,["لا يظهر عادة","أحيانًا","متكرر","غير متأكدة"]],
    ["sensitivity","هل تميل بشرتك إلى التحسس من منتجات العناية؟","safety",true,["لا","أحيانًا","نعم","غير متأكدة"]],
    ["known_allergy","هل تعرفين حساسية تجاه مكوّن عناية؟","safety",true,["لا","نعم","غير متأكدة"]],
    ["previous_reaction","هل سبق حدوث تفاعل قوي بعد منتج عناية؟","safety",true,["لا","نعم","غير متأكدة"]],
    ["prescription_topical","هل تستخدمين حاليًا منتجًا موضعيًا بوصفة؟","safety",true,["لا","نعم","أفضل عدم الإجابة"]],
    ["pregnancy","هل الحمل أو الرضاعة أمر ذو صلة الآن؟","safety",true,["لا","نعم","أفضل عدم الإجابة"]],
    ["open_wounds","هل توجد جروح مفتوحة أو حاجز جلدي متضرر بوضوح؟","screening",true,["لا","نعم"]],
    ["severe_irritation","هل يوجد تهيج شديد أو متفاقم أو مستمر؟","screening",true,["لا","نعم"]],
    ["suspected_infection","هل توجد علامة غير واضحة تعتقدين أنها قد تحتاج تقييمًا طبيًا؟","screening",true,["لا","نعم","غير متأكدة"]],
    ["recent_procedure","هل أجريتِ إجراءً جلديًا مهنيًا مؤخرًا؟","screening",true,["لا","نعم"]],
    ["cleanser","هل تستخدمين منظفًا؟","routine",false,["لا","نعم"]],
    ["moisturizer","هل تستخدمين مرطبًا؟","routine",false,["لا","نعم"]],
    ["sunscreen","هل تستخدمين واقي شمس؟","routine",false,["لا","أحيانًا","نعم"]],
    ["retinoid","هل تستخدمين ريتينويد ضمن روتينك؟","actives",false,["لا","نعم","غير متأكدة"]],
    ["exfoliating_acid","هل تستخدمين أحماض تقشير؟","actives",false,["لا","نعم","غير متأكدة"]],
    ["vitamin_c","هل تستخدمين فيتامين C؟","actives",false,["لا","نعم","غير متأكدة"]],
    ["main_goal","ما هدفك الأساسي من تنظيم الروتين؟","goals",true,["الترطيب","توازن الزيوت","ملمس أكثر نعومة بالمظهر","مظهر لون غير متجانس","دعم روتين عام"]],
    ["routine_preference","أي نمط تفضلين؟","preferences",true,["روتين بسيط","روتين تفصيلي","غير متأكدة"]]
  ] as const;
  for(let i=0;i<questions.length;i++){const [code,text,section,required,options]=questions[i];const q=await prisma.assessmentQuestion.upsert({where:{code_version:{code,version:1}},update:{templateId:template.id,sectionId:sections.get(section),textAr:text,sectionKey:section,isRequired:required,status:RecordStatus.ACTIVE,sortOrder:i},create:{templateId:template.id,sectionId:sections.get(section),code,version:1,textAr:text,sectionKey:section,type:"SINGLE_CHOICE",isRequired:required,isSensitive:section==="safety"||section==="screening",referralRelevant:section==="screening",requiresSpecialistReview:section==="safety",status:RecordStatus.ACTIVE,sortOrder:i,helpTextAr:"سؤال تطويري مبدئي يحتاج اعتماد المالكة ومختص مؤهل."}});for(let j=0;j<options.length;j++){const label=options[j],value=`v${j}`;await prisma.assessmentOption.upsert({where:{questionId_value:{questionId:q.id,value}},update:{labelAr:label,triggersReferral:["open_wounds","severe_irritation"].includes(code)&&j===1,triggersMoreInfo:["suspected_infection","prescription_topical","pregnancy","previous_reaction"].includes(code)&&j>0},create:{questionId:q.id,value,labelAr:label,sortOrder:j,triggersReferral:["open_wounds","severe_irritation"].includes(code)&&j===1,triggersMoreInfo:["suspected_infection","prescription_topical","pregnancy","previous_reaction"].includes(code)&&j>0}})}}
  const dependent=[
    ["allergy_detail","ما المكوّنات التي تعرفين أنها لا تناسبك؟","known_allergy","v1"],
    ["reaction_detail","صفي التفاعل السابق باختصار دون بيانات شخصية إضافية.","previous_reaction","v1"],
    ["prescription_detail","اكتبي اسم المنتج أو المكوّن الفعال إن كنت تعرفينه.","prescription_topical","v1"]
  ] as const;for(let i=0;i<dependent.length;i++){const [code,text,parentCode,show]=dependent[i],parent=await prisma.assessmentQuestion.findUniqueOrThrow({where:{code_version:{code:parentCode,version:1}}});await prisma.assessmentQuestion.upsert({where:{code_version:{code,version:1}},update:{textAr:text,parentQuestionId:parent.id,showWhenValue:show,status:RecordStatus.ACTIVE},create:{code,version:1,textAr:text,sectionKey:"safety",type:"LONG_TEXT",isRequired:true,isSensitive:true,status:RecordStatus.ACTIVE,sortOrder:100+i,parentQuestionId:parent.id,showWhenValue:show,maxLength:300,helpTextAr:"لا تكتبي تشخيصًا أو معلومات لا يحتاجها إعداد الإرشاد."}})}
  const ruleDefs=[["Severe irritation screen","severe_irritation","REFER_TO_SPECIALIST",100],["Open wound screen","open_wounds","REFER_TO_SPECIALIST",100],["Unclear infection concern","suspected_infection","NEEDS_MORE_INFORMATION",90],["Prescription review","prescription_topical","NEEDS_MORE_INFORMATION",80],["Pregnancy ingredient review","pregnancy","NEEDS_MORE_INFORMATION",80]] as const;for(const [name,questionCode,outcome,priority] of ruleDefs){const existing=await prisma.assessmentRule.findFirst({where:{templateId:template.id,name}});if(!existing)await prisma.assessmentRule.create({data:{templateId:template.id,name,questionCode,matchValue:"v1",outcome,priority,severity:"SAFETY",customerMessageAr:outcome==="REFER_TO_SPECIALIST"?"قد يكون من الأكثر أمانًا التحدث مع مختص مؤهل قبل إرشاد المنتجات.":"قد نحتاج معلومات إضافية أو مراجعة مهنية قبل إرشاد المنتجات.",internalMessage:"DEVELOPMENT ONLY — REQUIRES SPECIALIST APPROVAL",isProvisional:true,requiresSpecialistApproval:true}})}
  await prisma.assessmentQuestion.updateMany({where:{code:{in:dependent.map(x=>x[0])},version:1},data:{templateId:template.id,sectionId:sections.get("safety")}});
  const skinTypes=[["balanced","متوازنة"],["dry","جافة"],["oily","دهنية"],["combination","مختلطة"]] as const;for(const [slug,nameAr] of skinTypes)await prisma.skinType.upsert({where:{slug},update:{nameAr,isActive:true},create:{slug,nameAr,isActive:true,isDemo:true}});
  const concerns=[["hydration","ترطيب"],["balance","توازن الزيوت"],["texture","ملمس البشرة"],["tone-appearance","مظهر اللون"],["routine-support","دعم الروتين"]] as const;for(const [slug,nameAr] of concerns)await prisma.skinConcern.upsert({where:{slug},update:{nameAr,isActive:true},create:{slug,nameAr,isActive:true,isDemo:true}});
  const ingredientRows=[["jojoba-demo","زيت جوجوبا تجريبي"],["squalane-demo","سكوالان تجريبي"],["rosehip-demo","روزهِب تجريبي"],["fragrance-demo","عطر تجريبي"]] as const;for(const [slug,nameAr] of ingredientRows){const ingredient=await prisma.ingredient.upsert({where:{slug},update:{nameAr,isActive:true},create:{slug,nameAr,isActive:true,isDemo:true}});if(slug==="fragrance-demo")await prisma.productIngredientRestriction.upsert({where:{ingredientId_code:{ingredientId:ingredient.id,code:"DECLARED_FRAGRANCE_SENSITIVITY"}},update:{isActive:true},create:{ingredientId:ingredient.id,code:"DECLARED_FRAGRANCE_SENSITIVITY",labelAr:"تحسس عطر مذكور",isHardExclusion:true,requiresSpecialistApproval:true,approvalStatus:"PROVISIONAL",isActive:true}})}
  const productConfig:Record<string,{skin:string[];concerns:string[];ingredients:string[]}>={
    "daily-balance-oil":{skin:["balanced","oily","combination"],concerns:["balance","routine-support"],ingredients:["jojoba-demo","squalane-demo"]},
    "gentle-night-oil":{skin:["dry","balanced"],concerns:["hydration","texture"],ingredients:["squalane-demo","rosehip-demo"]},
    "simple-care-oil":{skin:["balanced","dry"],concerns:["routine-support","hydration"],ingredients:["jojoba-demo"]},
    "soft-routine-oil":{skin:["dry","balanced","combination"],concerns:["hydration","routine-support"],ingredients:["squalane-demo"]},
    "everyday-oil":{skin:["balanced","oily"],concerns:["balance","routine-support"],ingredients:["jojoba-demo","fragrance-demo"]}
  };
  for(const [slug,cfg] of Object.entries(productConfig)){const product=await prisma.product.findUnique({where:{slug}});if(!product)continue;for(const skinSlug of cfg.skin){const skin=await prisma.skinType.findUniqueOrThrow({where:{slug:skinSlug}});await prisma.productSkinCompatibility.upsert({where:{productId_skinTypeId:{productId:product.id,skinTypeId:skin.id}},update:{noteAr:"DEMO PROVISIONAL"},create:{productId:product.id,skinTypeId:skin.id,noteAr:"DEMO PROVISIONAL"}})}for(const concernSlug of cfg.concerns){const concern=await prisma.skinConcern.findUniqueOrThrow({where:{slug:concernSlug}});await prisma.productConcernMapping.upsert({where:{productId_skinConcernId:{productId:product.id,skinConcernId:concern.id}},update:{noteAr:"DEMO PROVISIONAL"},create:{productId:product.id,skinConcernId:concern.id,noteAr:"DEMO PROVISIONAL"}})}let order=0;for(const ingredientSlug of cfg.ingredients){const ingredient=await prisma.ingredient.findUniqueOrThrow({where:{slug:ingredientSlug}});await prisma.productIngredient.upsert({where:{productId_ingredientId:{productId:product.id,ingredientId:ingredient.id}},update:{displayOrder:order,noteAr:"DEMO PROVISIONAL"},create:{productId:product.id,ingredientId:ingredient.id,displayOrder:order,noteAr:"DEMO PROVISIONAL"}});order++}}
  const recConfig=await prisma.recommendationConfig.upsert({where:{key_version:{key:"deterministic-demo",version:1}},update:{status:RecordStatus.ACTIVE,approvalStatus:"PROVISIONAL",isProvisional:true,publishedAt:new Date()},create:{key:"deterministic-demo",nameAr:"إعداد توصيات حتمي - DEVELOPMENT ONLY",version:1,status:RecordStatus.ACTIVE,approvalStatus:"PROVISIONAL",engineVersion:"deterministic-v1",isProvisional:true,publishedAt:new Date()}});
  const weights=[["base","قاعدة مبدئية",40,0],["skin_type","توافق نوع البشرة",25,1],["concern","ارتباط الاهتمام",14,2],["simple_routine","روتين بسيط",8,3],["sensitivity_caution","حذر التحسس",-8,4]] as const;for(const [code,labelAr,weight,sortOrder] of weights)await prisma.recommendationScoreWeight.upsert({where:{configId_code:{configId:recConfig.id,code}},update:{labelAr,weight,sortOrder,isActive:true},create:{configId:recConfig.id,code,labelAr,weight,sortOrder,isActive:true}});
  const explanationTemplates=[["safe_notice","تنبيه السلامة","لا تمثل هذه النتيجة تشخيصًا طبيًا ولا ضمانًا للملاءمة."],["skin_type","نوع البشرة","يتوافق مع نوع البشرة الذي اخترتِه."],["concern","الاهتمام","يرتبط بالاهتمام الذي حددتِه."]] as const;for(const [code,labelAr,bodyAr] of explanationTemplates)await prisma.recommendationExplanationTemplate.upsert({where:{configId_code:{configId:recConfig.id,code}},update:{labelAr,bodyAr,isActive:true},create:{configId:recConfig.id,code,labelAr,bodyAr,isActive:true}});
  await prisma.recommendationConfig.upsert({where:{key_version:{key:"deterministic-demo",version:2}},update:{status:RecordStatus.DRAFT},create:{key:"deterministic-demo",nameAr:"مسودة توصيات مستقبلية - DEVELOPMENT ONLY",version:2,status:RecordStatus.DRAFT,approvalStatus:"PROVISIONAL",engineVersion:"deterministic-v1",isProvisional:true}});
}
main().finally(()=>prisma.$disconnect());
