"use server";
import {redirect} from "next/navigation";import {revalidatePath} from "next/cache";import {requireAdmin} from "@/server/auth/authorization";import {archiveTemplate,createTemplate,duplicateTemplate,publishTemplate,saveOption,saveQuestion,saveRule,saveSection} from "./admin";import {AssessmentOutcome,QuestionType} from "../../../generated/prisma/enums";
async function actor(){const x=await requireAdmin("assessments:configure");return{id:x.user.id,role:x.role};}const s=(f:FormData,k:string)=>String(f.get(k)||"");const b=(f:FormData,k:string)=>f.get(k)==="on";
export async function createTemplateAction(f:FormData){const row=await createTemplate(await actor(),{key:s(f,"key"),nameAr:s(f,"nameAr"),consentVersion:s(f,"consentVersion"),estimatedMinutes:s(f,"estimatedMinutes")});redirect(`/admin/assessments/templates/${row.id}`)}
export async function duplicateTemplateAction(id:string){const row=await duplicateTemplate(await actor(),id);redirect(`/admin/assessments/templates/${row.id}`)}
export async function sectionAction(templateId:string,id:string|undefined,f:FormData){await saveSection(await actor(),templateId,{key:s(f,"key"),titleAr:s(f,"titleAr"),descriptionAr:s(f,"descriptionAr"),sortOrder:s(f,"sortOrder")},id);revalidatePath(`/admin/assessments/templates/${templateId}`)}
export async function questionAction(templateId:string,id:string|undefined,f:FormData){await saveQuestion(await actor(),templateId,{code:s(f,"code"),sectionId:s(f,"sectionId"),textAr:s(f,"textAr"),helpTextAr:s(f,"helpTextAr"),type:s(f,"type") as QuestionType,isRequired:b(f,"isRequired"),isSensitive:b(f,"isSensitive"),sortOrder:s(f,"sortOrder"),parentQuestionId:s(f,"parentQuestionId"),showWhenValue:s(f,"showWhenValue")},id);revalidatePath(`/admin/assessments/templates/${templateId}`)}
export async function optionAction(templateId:string,questionId:string,id:string|undefined,f:FormData){await saveOption(await actor(),templateId,questionId,{value:s(f,"value"),labelAr:s(f,"labelAr"),sortOrder:s(f,"sortOrder"),triggersReferral:b(f,"triggersReferral"),triggersMoreInfo:b(f,"triggersMoreInfo")},id);revalidatePath(`/admin/assessments/templates/${templateId}`)}
export async function ruleAction(templateId:string,id:string|undefined,f:FormData){await saveRule(await actor(),templateId,{name:s(f,"name"),questionCode:s(f,"questionCode"),matchValue:s(f,"matchValue"),outcome:s(f,"outcome") as AssessmentOutcome,priority:s(f,"priority"),customerMessageAr:s(f,"customerMessageAr"),requiresSpecialistApproval:b(f,"requiresSpecialistApproval")},id);revalidatePath(`/admin/assessments/templates/${templateId}`)}
export async function publishTemplateAction(id:string,f:FormData){await publishTemplate(await actor(),id,s(f,"confirmation"));revalidatePath(`/admin/assessments/templates/${id}`)}
export async function archiveTemplateAction(id:string,f:FormData){await archiveTemplate(await actor(),id,s(f,"confirmation"));revalidatePath("/admin/assessments/templates")}
