import {AssessmentOutcome,QuestionType} from "../../../generated/prisma/enums";import {z} from "zod";
export type DraftQuestion={id:string;code:string;type:QuestionType;isRequired:boolean;parentQuestionId:string|null;showWhenValue:string|null;options:{id:string;value:string;triggersReferral:boolean;triggersMoreInfo:boolean}[]};
export type DraftAnswer={questionId:string;optionId?:string;valueText?:string;valueBoolean?:boolean;valueNumber?:number};
export const consentVersion="assessment-demo-v1";
export const answerSchema=z.object({questionId:z.string().uuid(),optionId:z.string().uuid().optional(),valueText:z.string().trim().max(500).optional(),valueBoolean:z.boolean().optional(),valueNumber:z.number().min(0).max(120).optional()});
export function visibleQuestions(questions:DraftQuestion[],answers:DraftAnswer[]){const map=new Map(answers.map(a=>[a.questionId,a])),byId=new Map(questions.map(q=>[q.id,q]));return questions.filter(q=>{if(!q.parentQuestionId)return true;const a=map.get(q.parentQuestionId),parent=byId.get(q.parentQuestionId),option=parent?.options.find(o=>o.id===a?.optionId);return q.showWhenValue===(option?.value||a?.valueText||String(a?.valueBoolean??""));});}
export function cleanHiddenAnswers(q:DraftQuestion[],a:DraftAnswer[]){const visible=new Set(visibleQuestions(q,a).map(x=>x.id));return a.filter(x=>visible.has(x.questionId));}
export function validateAnswers(q:DraftQuestion[],a:DraftAnswer[]){const visible=visibleQuestions(q,a),map=new Map(a.map(x=>[x.questionId,x]));const errors:string[]=[];for(const question of visible){const answer=map.get(question.id);if(question.isRequired&&!answer)errors.push(question.code);if(answer?.optionId&&!question.options.some(o=>o.id===answer.optionId))errors.push(`${question.code}:INVALID_OPTION`);}return errors;}
export function calculateProgress(q:DraftQuestion[],a:DraftAnswer[]){const visible=visibleQuestions(q,a).filter(x=>x.type!==QuestionType.INFORMATIONAL);if(!visible.length)return 0;const ids=new Set(a.map(x=>x.questionId));return Math.min(100,Math.round(visible.filter(x=>ids.has(x.id)).length/visible.length*100));}
export function evaluateSafety(q:DraftQuestion[],a:DraftAnswer[]){const errors=validateAnswers(q,a);if(errors.length)return{outcome:AssessmentOutcome.NEEDS_MORE_INFORMATION,message:"تحتاج بعض الإجابات الأساسية إلى الاستكمال قبل متابعة تجهيز الإرشاد."};const byId=new Map(q.map(x=>[x.id,x]));let more=false;for(const ans of a){const option=byId.get(ans.questionId)?.options.find(o=>o.id===ans.optionId);if(option?.triggersReferral)return{outcome:AssessmentOutcome.REFER_TO_SPECIALIST,message:"بناءً على إجاباتك، قد يكون من الأكثر أمانًا التحدث مع مختص مؤهل قبل إرشاد المنتجات."};if(option?.triggersMoreInfo)more=true;}if(more)return{outcome:AssessmentOutcome.NEEDS_MORE_INFORMATION,message:"تشير إجاباتك إلى أن معلومات إضافية أو مراجعة مهنية قد تكون مفيدة قبل إرشاد المنتجات."};return{outcome:AssessmentOutcome.READY_FOR_FUTURE_RECOMMENDATION,message:"اكتملت إجاباتك دون تشغيل حاجز سلامة مبدئي. مطابقة المنتجات ستُضاف في المرحلة السابعة بعد الاعتماد."};}
