ALTER TYPE "AssessmentStatus" ADD VALUE IF NOT EXISTS 'NEEDS_MORE_INFORMATION';
ALTER TYPE "AssessmentStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_FUTURE_RECOMMENDATION';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'YES_NO';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'LONG_TEXT';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'NUMBER';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'DATE';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'INFORMATIONAL';
CREATE TYPE "AssessmentOutcome" AS ENUM ('CONTINUE','NEEDS_MORE_INFORMATION','REFER_TO_SPECIALIST','BLOCK_PRODUCT_RECOMMENDATION','SHOW_SAFETY_NOTICE','READY_FOR_FUTURE_RECOMMENDATION');
