"use server";
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { randomUUID } from "crypto";import { requireAdmin } from "@/server/auth/authorization";import { adjustInventory,archiveProduct,confirmManualPayment,moderateReview,saveContent,saveCoupon,saveProduct,saveSettings,saveVariant,transitionOrder } from "./service";import { OrderStatus,ProductStatus,ReviewStatus } from "../../../generated/prisma/enums";
async function actor(permission:Parameters<typeof requireAdmin>[0]){const x=await requireAdmin(permission);return{id:x.user.id,role:x.role};}
const s=(f:FormData,k:string)=>String(f.get(k)||"");const b=(f:FormData,k:string)=>f.get(k)==="on";
export async function productAction(id:string|undefined,f:FormData){await saveProduct(await actor("products:write"),{nameAr:s(f,"nameAr"),slug:s(f,"slug"),categoryId:s(f,"categoryId"),shortDescriptionAr:s(f,"shortDescriptionAr"),descriptionAr:s(f,"descriptionAr"),status:s(f,"status") as ProductStatus,isFeatured:b(f,"isFeatured"),sortOrder:s(f,"sortOrder")},id);revalidatePath("/admin/products");redirect("/admin/products");}
export async function archiveProductAction(id:string){await archiveProduct(await actor("products:write"),id);revalidatePath("/admin/products");}
export async function variantAction(id:string|undefined,f:FormData){const productId=s(f,"productId");await saveVariant(await actor("products:write"),{productId,sku:s(f,"sku"),nameAr:s(f,"nameAr"),sizeLabel:s(f,"sizeLabel"),price:s(f,"price"),currency:s(f,"currency"),stock:s(f,"stock"),lowStockThreshold:s(f,"lowStockThreshold"),isDefault:b(f,"isDefault")},id);revalidatePath(`/admin/products/${productId}`);}
export async function inventoryAction(f:FormData){await adjustInventory(await actor("inventory:write"),{variantId:s(f,"variantId"),type:s(f,"type"),quantity:s(f,"quantity"),reason:s(f,"reason"),note:s(f,"note"),idempotencyKey:s(f,"idempotencyKey")||randomUUID()});revalidatePath("/admin/inventory");}
export async function orderTransitionAction(reference:string,f:FormData){await transitionOrder(await actor("orders:write"),reference,s(f,"status") as OrderStatus,s(f,"note"));revalidatePath(`/admin/orders/${reference}`);}
export async function confirmPaymentAction(reference:string){await confirmManualPayment(await actor("payments:confirm"),reference);revalidatePath(`/admin/orders/${reference}`);}
export async function couponAction(id:string|undefined,f:FormData){await saveCoupon(await actor("coupons:write"),{code:s(f,"code"),type:s(f,"type"),value:s(f,"value"),minimumSubtotal:s(f,"minimumSubtotal")||undefined,maximumDiscount:s(f,"maximumDiscount")||undefined,usageLimit:s(f,"usageLimit")||undefined,perCustomerLimit:s(f,"perCustomerLimit"),isActive:b(f,"isActive"),startsAt:s(f,"startsAt")||undefined,endsAt:s(f,"endsAt")||undefined},id);revalidatePath("/admin/coupons");}
export async function reviewAction(id:string,f:FormData){await moderateReview(await actor("reviews:moderate"),id,{status:s(f,"status") as ReviewStatus,reason:s(f,"reason")});revalidatePath("/admin/reviews");}
export async function settingsAction(f:FormData){await saveSettings(await actor("settings:write"),{storeName:s(f,"storeName"),currencyCode:s(f,"currencyCode"),currencyLabel:s(f,"currencyLabel"),shippingFlatRate:s(f,"shippingFlatRate"),freeShippingThreshold:s(f,"freeShippingThreshold")?Number(s(f,"freeShippingThreshold")):null,codEnabled:b(f,"codEnabled"),manualTransferEnabled:b(f,"manualTransferEnabled"),cancellationWindowHours:s(f,"cancellationWindowHours"),contactEmail:s(f,"contactEmail"),contactPhone:s(f,"contactPhone"),instagram:s(f,"instagram"),whatsapp:s(f,"whatsapp"),maintenanceNotice:s(f,"maintenanceNotice")});revalidatePath("/admin/settings");}
export async function contentAction(f:FormData){await saveContent(await actor("content:write"),{key:s(f,"key"),type:s(f,"type"),titleAr:s(f,"titleAr"),bodyAr:s(f,"bodyAr"),url:s(f,"url")||undefined});revalidatePath("/admin/content");}
