import { OrderStatus,PaymentStatus,ProductStatus,ReviewStatus } from "../../../generated/prisma/enums";
import { z } from "zod";

export const slugify=(v:string)=>v.trim().toLowerCase().normalize("NFKD").replace(/[^a-z0-9\u0600-\u06ff]+/g,"-").replace(/^-|-$/g,"").slice(0,80);
const text=(max:number)=>z.string().trim().min(2).max(max);
export const productSchema=z.object({nameAr:text(120),slug:z.string().transform(slugify).pipe(z.string().min(2).max(80)),categoryId:z.string().uuid(),shortDescriptionAr:z.string().trim().max(240).optional(),descriptionAr:z.string().trim().max(4000).optional(),status:z.nativeEnum(ProductStatus),isFeatured:z.boolean().default(false),sortOrder:z.coerce.number().int().min(0).max(10000)});
export const variantSchema=z.object({productId:z.string().uuid(),sku:z.string().trim().toUpperCase().regex(/^[A-Z0-9-]{3,40}$/),nameAr:text(80),sizeLabel:z.string().trim().max(40).optional(),price:z.coerce.number().min(0).max(1_000_000),currency:z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/),stock:z.coerce.number().int().min(0),lowStockThreshold:z.coerce.number().int().min(0).max(100000),isDefault:z.boolean().default(false)});
export const adjustmentSchema=z.object({variantId:z.string().uuid(),type:z.enum(["MANUAL_ADJUSTMENT","RESTOCK","DAMAGE","CORRECTION"]),quantity:z.coerce.number().int().refine(v=>v!==0),reason:text(160),note:z.string().trim().max(500).optional(),idempotencyKey:z.string().uuid()});
export const couponAdminSchema=z.object({code:z.string().trim().toUpperCase().regex(/^[A-Z0-9_-]{3,30}$/),type:z.enum(["FIXED","PERCENTAGE"]),value:z.coerce.number().positive().max(1_000_000),minimumSubtotal:z.coerce.number().min(0).optional(),maximumDiscount:z.coerce.number().positive().optional(),usageLimit:z.coerce.number().int().positive().optional(),perCustomerLimit:z.coerce.number().int().positive().max(100),isActive:z.boolean(),startsAt:z.coerce.date().optional(),endsAt:z.coerce.date().optional()}).refine(v=>!v.startsAt||!v.endsAt||v.endsAt>v.startsAt,{message:"INVALID_DATE_RANGE"}).refine(v=>v.type!=="PERCENTAGE"||v.value<=100,{message:"INVALID_PERCENTAGE"});
export const reviewSchema=z.object({status:z.nativeEnum(ReviewStatus),reason:text(300)});
const safeUrl=z.string().url().refine(v=>/^https?:\/\//i.test(v)).or(z.literal(""));
export const settingsSchema=z.object({storeName:text(100),currencyCode:z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/),currencyLabel:text(20),shippingFlatRate:z.coerce.number().min(0),freeShippingThreshold:z.coerce.number().min(0).nullable(),codEnabled:z.boolean(),manualTransferEnabled:z.boolean(),cancellationWindowHours:z.coerce.number().int().min(0).max(720),contactEmail:z.string().email().or(z.literal("")),contactPhone:z.string().trim().max(30),instagram:safeUrl,whatsapp:safeUrl,maintenanceNotice:z.string().trim().max(300)});
export const transitions:Partial<Record<OrderStatus,readonly OrderStatus[]>>={PENDING_PAYMENT:[OrderStatus.PAYMENT_REVIEW,OrderStatus.CONFIRMED,OrderStatus.CANCELLED],PAYMENT_REVIEW:[OrderStatus.CONFIRMED,OrderStatus.CANCELLED],CONFIRMED:[OrderStatus.PREPARING,OrderStatus.CANCELLED],PREPARING:[OrderStatus.READY_TO_SHIP,OrderStatus.CANCELLED],READY_TO_SHIP:[OrderStatus.SHIPPED,OrderStatus.CANCELLED],SHIPPED:[OrderStatus.DELIVERED,OrderStatus.DELIVERY_FAILED],DELIVERY_FAILED:[OrderStatus.SHIPPED,OrderStatus.CANCELLED]};
export const canTransition=(from:OrderStatus,to:OrderStatus)=>transitions[from]?.includes(to)??false;
export const canConfirmPayment=(method:string,status:PaymentStatus)=>method==="MANUAL_BANK_TRANSFER"&&(status===PaymentStatus.AWAITING_TRANSFER||status===PaymentStatus.PAYMENT_REVIEW);
const secretKey=/password|token|secret|authorization|cookie|private|reset/i;
export function redactAudit(value:unknown):unknown{if(Array.isArray(value))return value.map(redactAudit);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([k])=>!secretKey.test(k)).map(([k,v])=>[k,redactAudit(v)]));return typeof value==="string"&&value.length>300?`${value.slice(0,300)}…`:value;}
export const sanitizePlainText=(v:string)=>v.replace(/<[^>]*>/g,"").replace(/[<>]/g,"").trim();
