import { Prisma,OrderStatus,PaymentStatus,ProductStatus,UserRole } from "../../../generated/prisma/client";
import { getDb } from "@/server/db/client";
import { assertPermission,type Permission } from "@/server/auth/authorization";
import { adjustmentSchema,canConfirmPayment,canTransition,couponAdminSchema,productSchema,redactAudit,reviewSchema,sanitizePlainText,settingsSchema,variantSchema } from "./rules";

type Actor={id:string;role:UserRole};
async function audit(tx:Prisma.TransactionClient,actor:Actor,action:string,resourceType:string,resourceId:string|undefined,metadata?:unknown,outcome="SUCCESS"){await tx.auditLog.create({data:{actorUserId:actor.id,action,resourceType,resourceId,outcome,metadata:redactAudit(metadata) as Prisma.InputJsonValue|undefined}});}
const authorize=(a:Actor,p:Permission)=>assertPermission(a.role,p);

export async function saveProduct(actor:Actor,input:unknown,id?:string){authorize(actor,"products:write");const data=productSchema.parse(input);return getDb().$transaction(async tx=>{const duplicate=await tx.product.findFirst({where:{slug:data.slug,...(id?{id:{not:id}}:{})},select:{id:true}});if(duplicate)throw new Error("SLUG_EXISTS");const product=id?await tx.product.update({where:{id},data}):await tx.product.create({data});await audit(tx,actor,id?"PRODUCT_UPDATED":"PRODUCT_CREATED","Product",product.id,{slug:data.slug,status:data.status});return product;});}
export async function archiveProduct(actor:Actor,id:string){authorize(actor,"products:write");return getDb().$transaction(async tx=>{const p=await tx.product.update({where:{id},data:{status:ProductStatus.ARCHIVED,deletedAt:new Date()}});await audit(tx,actor,"PRODUCT_ARCHIVED","Product",id);return p;});}
export async function saveVariant(actor:Actor,input:unknown,id?:string){authorize(actor,"products:write");const data=variantSchema.parse(input);return getDb().$transaction(async tx=>{if(data.isDefault)await tx.productVariant.updateMany({where:{productId:data.productId,...(id?{id:{not:id}}:{})},data:{isDefault:false}});const existing=id?await tx.productVariant.findUniqueOrThrow({where:{id}}):null;const variant=id?await tx.productVariant.update({where:{id},data}):await tx.productVariant.create({data});if(existing&&existing.stock!==data.stock){await tx.inventoryMovement.create({data:{variantId:variant.id,type:"CORRECTION",quantity:data.stock-existing.stock,balanceAfter:data.stock,actorUserId:actor.id,reason:"تعديل المخزون ضمن تحرير المتغير"}});}await audit(tx,actor,id?"VARIANT_UPDATED":"VARIANT_CREATED","ProductVariant",variant.id,{sku:data.sku});return variant;});}
export async function adjustInventory(actor:Actor,input:unknown){authorize(actor,"inventory:write");const data=adjustmentSchema.parse(input);return getDb().$transaction(async tx=>{const prior=await tx.inventoryMovement.findUnique({where:{idempotencyKey:data.idempotencyKey}});if(prior)return prior;const variant=await tx.productVariant.findUniqueOrThrow({where:{id:data.variantId}});const next=variant.stock+data.quantity;if(next<0)throw new Error("NEGATIVE_STOCK");await tx.productVariant.update({where:{id:variant.id},data:{stock:next}});const movement=await tx.inventoryMovement.create({data:{...data,balanceAfter:next,actorUserId:actor.id}});await audit(tx,actor,"INVENTORY_ADJUSTED","ProductVariant",variant.id,{type:data.type,quantity:data.quantity,balanceAfter:next,reason:data.reason});return movement;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function transitionOrder(actor:Actor,reference:string,to:OrderStatus,note?:string){authorize(actor,"orders:write");return getDb().$transaction(async tx=>{const order=await tx.order.findUniqueOrThrow({where:{reference},include:{items:true}});if(order.status===to)return order;if(!canTransition(order.status,to))throw new Error("INVALID_TRANSITION");if(to===OrderStatus.CANCELLED){for(const item of order.items){if(!item.variantId)continue;const exists=await tx.inventoryMovement.findUnique({where:{orderId_variantId_type:{orderId:order.id,variantId:item.variantId,type:"CANCELLATION_RESTORE"}}});if(!exists){const v=await tx.productVariant.update({where:{id:item.variantId},data:{stock:{increment:item.quantity}}});await tx.inventoryMovement.create({data:{variantId:item.variantId,orderId:order.id,type:"CANCELLATION_RESTORE",quantity:item.quantity,balanceAfter:v.stock,actorUserId:actor.id,reason:"إلغاء إداري للطلب"}});}}}const updated=await tx.order.update({where:{id:order.id},data:{status:to,...(to===OrderStatus.CANCELLED?{cancelledAt:new Date(),paymentStatus:PaymentStatus.CANCELLED}:{}),statusHistory:{create:{fromStatus:order.status,toStatus:to,noteAr:note?.slice(0,300)||"تحديث بواسطة إدارة المتجر."}}}});await audit(tx,actor,"ORDER_STATUS_CHANGED","Order",order.id,{from:order.status,to});return updated;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function confirmManualPayment(actor:Actor,reference:string){authorize(actor,"payments:confirm");return getDb().$transaction(async tx=>{const o=await tx.order.findUniqueOrThrow({where:{reference}});if(o.paymentStatus===PaymentStatus.PAID)return o;if(!canConfirmPayment(o.paymentMethod,o.paymentStatus))throw new Error("PAYMENT_CONFIRMATION_NOT_ALLOWED");const next=o.status===OrderStatus.PENDING_PAYMENT?OrderStatus.CONFIRMED:o.status;const updated=await tx.order.update({where:{id:o.id},data:{paymentStatus:PaymentStatus.PAID,paymentConfirmedAt:new Date(),paymentConfirmedById:actor.id,status:next,...(next!==o.status?{statusHistory:{create:{fromStatus:o.status,toStatus:next,noteAr:"تم تأكيد التحويل اليدوي بواسطة الإدارة."}}}:{})}});await audit(tx,actor,"MANUAL_PAYMENT_CONFIRMED","Order",o.id,{reference});return updated;});}
export async function saveCoupon(actor:Actor,input:unknown,id?:string){authorize(actor,"coupons:write");const data=couponAdminSchema.parse(input);return getDb().$transaction(async tx=>{const coupon=id?await tx.coupon.update({where:{id},data:{...data,currency:data.type==="FIXED"?"XXX":null,isDemo:true}}):await tx.coupon.create({data:{...data,currency:data.type==="FIXED"?"XXX":null,isDemo:true}});await audit(tx,actor,id?"COUPON_UPDATED":"COUPON_CREATED","Coupon",coupon.id,{code:data.code});return coupon;});}
export async function moderateReview(actor:Actor,id:string,input:unknown){authorize(actor,"reviews:moderate");const data=reviewSchema.parse(input);return getDb().$transaction(async tx=>{const review=await tx.review.update({where:{id},data:{status:data.status,moderationReason:data.reason,moderatedAt:new Date(),moderatedById:actor.id}});await audit(tx,actor,"REVIEW_MODERATED","Review",id,{status:data.status});return review;});}
export async function saveSettings(actor:Actor,input:unknown){authorize(actor,"settings:write");const value=settingsSchema.parse(input);return getDb().$transaction(async tx=>{const result=await tx.siteSetting.upsert({where:{key:"store_operations"},create:{key:"store_operations",value,isPublic:false},update:{value}});await audit(tx,actor,"SETTINGS_UPDATED","SiteSetting",result.id,{fields:Object.keys(value)});return result;});}
export async function saveContent(actor:Actor,input:{key:string;type:string;titleAr:string;bodyAr:string;url?:string}){authorize(actor,"content:write");const key=input.key.trim().toLowerCase().replace(/[^a-z0-9_-]/g,"").slice(0,80),type=input.type.trim().toUpperCase().replace(/[^A-Z_]/g,"").slice(0,40);const titleAr=sanitizePlainText(input.titleAr).slice(0,160),bodyAr=sanitizePlainText(input.bodyAr).slice(0,2000),url=input.url?.trim();if(key.length<3||type.length<3||!titleAr||!bodyAr)throw new Error("INVALID_CONTENT");if(url&&!/^https?:\/\//i.test(url))throw new Error("UNSAFE_URL");return getDb().$transaction(async tx=>{const row=await tx.contentEntry.upsert({where:{key},create:{key,type,titleAr,bodyAr,url,status:"ACTIVE"},update:{type,titleAr,bodyAr,url}});await audit(tx,actor,"CONTENT_SAVED","ContentEntry",row.id,{key,type});return row;});}
export async function changeUserRole(actor:Actor,userId:string,role:UserRole){authorize(actor,"team:manage");if(actor.id===userId)throw new Error("SELF_ROLE_CHANGE_FORBIDDEN");if(role===UserRole.CUSTOMER||role===UserRole.SPECIALIST)throw new Error("INVALID_ADMIN_ROLE");return getDb().$transaction(async tx=>{const user=await tx.user.update({where:{id:userId},data:{role}});await audit(tx,actor,"USER_ROLE_CHANGED","User",userId,{role});return user;});}
